version: '3.9'
services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1
    networks:
      - my-network
    volumes:
      - ./data/mysql/data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network
    depends_on:
      - mysql
networks:
  my-network:
    driver: bridge
    name: my-network